// <auto-generated />
using DealsService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DealsService.DataAccess.Migrations
{
    [DbContext(typeof(DealsDbContext))]
    partial class DealsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DealsService.Models.Deal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<double?>("AiScore")
                        .HasColumnType("double precision")
                        .HasColumnName("ai_score");

                    b.Property<string>("AiScoreRationale")
                        .HasColumnType("text")
                        .HasColumnName("ai_score_rationale");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("DeadReason")
                        .HasColumnType("text")
                        .HasColumnName("dead_reason");

                    b.Property<double?>("EquityMultiple")
                        .HasColumnType("double precision")
                        .HasColumnName("equity_multiple");

                    b.Property<string>("MetroArea")
                        .HasColumnType("text")
                        .HasColumnName("metro_area");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("OfferPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("offer_price");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<double?>("ProjectedCapRate")
                        .HasColumnType("double precision")
                        .HasColumnName("projected_cap_rate");

                    b.Property<string>("ProjectedCloseDate")
                        .HasColumnType("text")
                        .HasColumnName("projected_close_date");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_name");

                    b.Property<string>("PropertyType")
                        .HasColumnType("text")
                        .HasColumnName("property_type");

                    b.Property<string>("RiskFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_flags");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("StageEnteredAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage_entered_at");

                    b.Property<double?>("TargetIrr")
                        .HasColumnType("double precision")
                        .HasColumnName("target_irr");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deals");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_deals_owner_id");

                    b.HasIndex("PropertyId")
                        .IsUnique()
                        .HasDatabaseName("ix_deals_property_id_active")
                        .HasFilter("stage NOT IN ('Acquired', 'Dead')");

                    b.HasIndex("Stage")
                        .HasDatabaseName("ix_deals_stage");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("DealsService.Models.DealComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("DealId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deal_id");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ai_generated");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_deal_comments");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_deal_comments_deal_id");

                    b.ToTable("deal_comments", (string)null);
                });

            modelBuilder.Entity("DealsService.Models.DealDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<string>("DealId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deal_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_deal_documents");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_deal_documents_deal_id");

                    b.ToTable("deal_documents", (string)null);
                });

            modelBuilder.Entity("DealsService.Models.DealStageHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ChangedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_by_id");

                    b.Property<int?>("DaysInStage")
                        .HasColumnType("integer")
                        .HasColumnName("days_in_stage");

                    b.Property<string>("DealId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deal_id");

                    b.Property<string>("FromStage")
                        .HasColumnType("text")
                        .HasColumnName("from_stage");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ToStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_stage");

                    b.HasKey("Id")
                        .HasName("pk_deal_stage_history");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_deal_stage_history_deal_id");

                    b.ToTable("deal_stage_history", (string)null);
                });

            modelBuilder.Entity("DealsService.Models.DealTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeId")
                        .HasColumnType("text")
                        .HasColumnName("assignee_id");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("text")
                        .HasColumnName("completed_at");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("DealId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deal_id");

                    b.Property<string>("DueDate")
                        .HasColumnType("text")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsFromTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_template");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_deal_tasks");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_deal_tasks_deal_id");

                    b.ToTable("deal_tasks", (string)null);
                });

            modelBuilder.Entity("DealsService.Models.DealComment", b =>
                {
                    b.HasOne("DealsService.Models.Deal", null)
                        .WithMany("Comments")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deal_comments_deals_deal_id");
                });

            modelBuilder.Entity("DealsService.Models.DealDocument", b =>
                {
                    b.HasOne("DealsService.Models.Deal", null)
                        .WithMany("Documents")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deal_documents_deals_deal_id");
                });

            modelBuilder.Entity("DealsService.Models.DealStageHistory", b =>
                {
                    b.HasOne("DealsService.Models.Deal", null)
                        .WithMany("History")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deal_stage_history_deals_deal_id");
                });

            modelBuilder.Entity("DealsService.Models.DealTask", b =>
                {
                    b.HasOne("DealsService.Models.Deal", null)
                        .WithMany("Tasks")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deal_tasks_deals_deal_id");
                });

            modelBuilder.Entity("DealsService.Models.Deal", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Documents");

                    b.Navigation("History");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
