// <auto-generated />
using ListingsService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ListingsService.DataAccess.Migrations
{
    [DbContext(typeof(ListingsDbContext))]
    partial class ListingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ListingsService.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MetroArea")
                        .HasColumnType("text")
                        .HasColumnName("metro_area");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("PropertyId")
                        .IsUnique()
                        .HasDatabaseName("ix_addresses_property_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("ListingsService.Models.Property", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<double?>("AskingPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("asking_price");

                    b.Property<double?>("CapRate")
                        .HasColumnType("double precision")
                        .HasColumnName("cap_rate");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("text")
                        .HasColumnName("description_text");

                    b.Property<double?>("LeasableSqft")
                        .HasColumnType("double precision")
                        .HasColumnName("leasable_sqft");

                    b.Property<string>("ListedAt")
                        .HasColumnType("text")
                        .HasColumnName("listed_at");

                    b.Property<double?>("LotSizeAcres")
                        .HasColumnType("double precision")
                        .HasColumnName("lot_size_acres");

                    b.Property<double?>("MarketCapRateBenchmark")
                        .HasColumnType("double precision")
                        .HasColumnName("market_cap_rate_benchmark");

                    b.Property<double?>("Noi")
                        .HasColumnType("double precision")
                        .HasColumnName("noi");

                    b.Property<double?>("OccupancyRate")
                        .HasColumnType("double precision")
                        .HasColumnName("occupancy_rate");

                    b.Property<string>("PropertySubtype")
                        .HasColumnType("text")
                        .HasColumnName("property_subtype");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_type");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<double?>("TotalSqft")
                        .HasColumnType("double precision")
                        .HasColumnName("total_sqft");

                    b.Property<int?>("UnitCount")
                        .HasColumnType("integer")
                        .HasColumnName("unit_count");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.Property<double?>("Year1NoiEstimate")
                        .HasColumnType("double precision")
                        .HasColumnName("year1_noi_estimate");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("ListingsService.Models.PropertyFeature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("FeatureCategory")
                        .HasColumnType("text")
                        .HasColumnName("feature_category");

                    b.Property<string>("FeatureName")
                        .HasColumnType("text")
                        .HasColumnName("feature_name");

                    b.Property<string>("FeatureValue")
                        .HasColumnType("text")
                        .HasColumnName("feature_value");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.HasKey("Id")
                        .HasName("pk_property_features");

                    b.HasIndex("PropertyId", "FeatureName")
                        .IsUnique()
                        .HasDatabaseName("ix_property_features_property_id_feature_name");

                    b.ToTable("property_features", (string)null);
                });

            modelBuilder.Entity("ListingsService.Models.PropertyMedia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("MediaType")
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("property_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_property_media");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_property_media_property_id");

                    b.ToTable("property_media", (string)null);
                });

            modelBuilder.Entity("ListingsService.Models.Address", b =>
                {
                    b.HasOne("ListingsService.Models.Property", "Property")
                        .WithOne("Address")
                        .HasForeignKey("ListingsService.Models.Address", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ListingsService.Models.PropertyFeature", b =>
                {
                    b.HasOne("ListingsService.Models.Property", "Property")
                        .WithMany("Features")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_features_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ListingsService.Models.PropertyMedia", b =>
                {
                    b.HasOne("ListingsService.Models.Property", "Property")
                        .WithMany("Media")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_media_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ListingsService.Models.Property", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Features");

                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
