// <auto-generated />
using DocumentsService.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocumentsService.DataAccess.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20260723220855_DropDocumentText")]
    partial class DropDocumentText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentsService.Models.DocumentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConfirmedAt")
                        .HasColumnType("text")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("DealId")
                        .HasColumnType("text")
                        .HasColumnName("deal_id");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("text")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_document_records");

                    b.HasIndex("DealId")
                        .HasDatabaseName("ix_document_records_deal_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_document_records_status");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_document_records_storage_key");

                    b.ToTable("document_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
