#!/usr/bin/env python3
"""Measure what a user actually waits for, across the four shapes of AI question.

Single runs are all this feature has ever had, and a single run cannot say whether
AssistantOptions.WallClockSeconds (90) is a safety limit or a routine event. A question
that hits it is *truncated*: the loop stops early and the model is told to report what it
could not check, so the answer gets worse, not merely later. That makes P95 the number
that matters, and P95 needs a sample.

Four shapes, because they cost wildly different amounts of wall clock:

  single-tool       one pipeline_summary call, no retrieval          — the floor
  structured-only   one search_deals call over OpenSearch            — cheap
  cross-corpus      search_deals, then a scoped document retrieval   — the headline
                    per candidate; embeds a query and runs a
                    cross-encoder for each one
  deal-qa           the single-call JSON endpoint, one retrieval     — the other feature

Timed twice on purpose. The `done` SSE event carries the server's own wall clock (the
figure now persisted to ai_question_log.total_latency_ms); this script also times the
request from the client side. The gap between them is network plus SSE flush, and the two
agreeing is what proves the new column measures the right thing. Neither is the sum of
ai_request_log.latency_ms, which is model time only — that sum is reported too, from the
database, because the difference is tool execution and is the thing worth knowing.

Runs sequentially. Concurrency would be a different experiment: it would measure
contention against tei-rerank and OpenSearch, not what one user waits for.

Usage:
    python3 scripts/bench_assistant.py                    # 5 repeats x 4 shapes
    python3 scripts/bench_assistant.py --repeats 2        # smoke
    python3 scripts/bench_assistant.py --shapes cross-corpus
    python3 scripts/bench_assistant.py --out run.json
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

AUTH_URL = "http://localhost:5300"
AI_URL = "http://localhost:5700"
MANIFEST = Path(__file__).resolve().parent.parent / "seed-manifest.json"

# Generous: the point of the exercise is to observe questions that run long, and a client
# timeout below the server's own budget would censor exactly the samples P95 is made of.
TIMEOUT = 300


def login(email: str, password: str) -> str:
    body = json.dumps({"email": email, "password": password}).encode()
    req = urllib.request.Request(
        f"{AUTH_URL}/auth/v1/login", data=body, method="POST",
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)["data"]["accessToken"]


def pick_deal(manifest_path: Path) -> tuple[str, str]:
    """A deal with documents, so Deal Q&A has something to retrieve from.

    Taken from the seed manifest rather than hardcoded — the ids are regenerated by
    seed_deal_documents.py and a stale one would silently measure the empty-corpus path,
    which returns in milliseconds without a model call and would drag P50 to the floor.
    """
    rows = json.loads(manifest_path.read_text())
    if not rows:
        sys.exit(f"{manifest_path} is empty — run scripts/seed_deal_documents.py first.")
    # Prefer a deal carrying an offering memorandum: the prose documents are the ones a
    # question about tenants or condition can actually be answered from.
    preferred = [r for r in rows if r.get("fileType") == "OfferingMemorandum"]
    row = (preferred or rows)[0]
    return row["dealId"], row["dealName"]


SHAPES = {
    "single-tool": {
        "endpoint": "assistant",
        "question": "How many deals are in underwriting?",
        "why": "one pipeline_summary call, no retrieval",
    },
    "structured-only": {
        "endpoint": "assistant",
        "question": "Show me industrial deals in Denver.",
        "why": "one search_deals call, no documents",
    },
    "cross-corpus": {
        "endpoint": "assistant",
        "question": "Which industrial deals are stalling, and what do their documents say?",
        "why": "structured search, then a scoped retrieval per candidate",
    },
    "deal-qa": {
        "endpoint": "deal-qa",
        "question": "What does the offering memorandum say about the tenants and the condition of the property?",
        "why": "single-call JSON endpoint, one retrieval",
    },
}


def ask_assistant(token: str, question: str) -> dict:
    """POST /ai/v1/ask and read the SSE stream to its `done` event."""
    body = json.dumps({"question": question}).encode()
    req = urllib.request.Request(
        f"{AI_URL}/ai/v1/ask", data=body, method="POST",
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {token}",
                 "Accept": "text/event-stream"})

    done: dict = {}
    tools: list[str] = []
    answer_chars = 0
    error: str | None = None
    first_byte: float | None = None

    started = time.perf_counter()
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        event = None
        for raw in resp:
            if first_byte is None:
                first_byte = time.perf_counter() - started
            line = raw.decode("utf-8").rstrip("\n")
            if line.startswith("event:"):
                event = line[6:].strip()
            elif line.startswith("data:"):
                payload = json.loads(line[5:].strip())
                if event == "done":
                    done = payload
                elif event == "delta":
                    answer_chars += len(payload.get("text", ""))
                elif event == "tool":
                    tools.append(payload.get("tool", "?"))
                elif event == "error":
                    error = payload.get("code", "ERROR")
    client_ms = int((time.perf_counter() - started) * 1000)

    return {
        "client_ms": client_ms,
        "ttfb_ms": int((first_byte or 0) * 1000),
        "server_ms": done.get("latencyMs"),
        "iterations": done.get("iterations"),
        "tool_calls": done.get("toolCalls"),
        "truncated": done.get("truncated"),
        "tools": tools,
        "answer_chars": answer_chars,
        "error": error,
    }


def ask_deal_qa(token: str, deal_id: str, question: str) -> dict:
    body = json.dumps({"question": question}).encode()
    req = urllib.request.Request(
        f"{AI_URL}/ai/v1/deals/{deal_id}/ask", data=body, method="POST",
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {token}"})

    started = time.perf_counter()
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        payload = json.load(resp)["data"]
    client_ms = int((time.perf_counter() - started) * 1000)

    return {
        "client_ms": client_ms,
        "ttfb_ms": client_ms,          # no streaming: first byte is the whole answer
        "server_ms": payload.get("latencyMs"),
        "iterations": 1,
        "tool_calls": 0,
        "truncated": False,
        "tools": [],
        "answer_chars": len(payload.get("answer", "")),
        "error": None,
        "chunks": payload.get("retrievedChunkCount"),
        "answered_from_documents": payload.get("answeredFromDocuments"),
    }


def percentile(values: list[float], p: float) -> float:
    """Linear interpolation between closest ranks — the same definition Postgres's
    percentile_cont uses, so the two reports agree rather than differing by a rank."""
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return float(ordered[0])
    rank = p * (len(ordered) - 1)
    low = int(rank)
    high = min(low + 1, len(ordered) - 1)
    return ordered[low] + (ordered[high] - ordered[low]) * (rank - low)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repeats", type=int, default=5,
                    help="runs per shape (default 5)")
    ap.add_argument("--shapes", nargs="*", choices=sorted(SHAPES), default=sorted(SHAPES))
    ap.add_argument("--email", default="admin@proptrack.local")
    ap.add_argument("--password", default="ChangeMe123!")
    ap.add_argument("--out", type=Path, help="write raw per-run rows here as JSON")
    args = ap.parse_args()

    try:
        token = login(args.email, args.password)
    except urllib.error.URLError as ex:
        print(f"Could not reach auth-service at {AUTH_URL}: {ex}\n"
              f"Is the stack up? docker compose up -d", file=sys.stderr)
        return 1

    deal_id, deal_name = pick_deal(MANIFEST)
    run_start = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime())

    total = len(args.shapes) * args.repeats
    print(f"{total} question(s): {len(args.shapes)} shape(s) x {args.repeats} repeat(s), sequential.")
    print(f"Deal Q&A deal: {deal_name} ({deal_id})")
    print(f"Run started (UTC): {run_start}\n")

    rows: list[dict] = []
    for shape in args.shapes:
        spec = SHAPES[shape]
        print(f"--- {shape}  ({spec['why']})")
        print(f"    \"{spec['question']}\"")
        for i in range(args.repeats):
            try:
                if spec["endpoint"] == "assistant":
                    result = ask_assistant(token, spec["question"])
                else:
                    result = ask_deal_qa(token, deal_id, spec["question"])
            except urllib.error.HTTPError as ex:
                detail = ex.read().decode("utf-8", "replace")[:200]
                print(f"    {i + 1}/{args.repeats}  HTTP {ex.code}: {detail}")
                rows.append({"shape": shape, "run": i + 1, "http_error": ex.code})
                continue
            except (urllib.error.URLError, TimeoutError) as ex:
                print(f"    {i + 1}/{args.repeats}  failed: {ex}")
                rows.append({"shape": shape, "run": i + 1, "error": str(ex)})
                continue

            result |= {"shape": shape, "run": i + 1}
            rows.append(result)

            flags = []
            if result["truncated"]:
                flags.append("TRUNCATED")
            if result["error"]:
                flags.append(result["error"])
            print(f"    {i + 1}/{args.repeats}  {result['client_ms'] / 1000:6.1f}s client"
                  f"  {(result['server_ms'] or 0) / 1000:6.1f}s server"
                  f"  ttfb {result['ttfb_ms'] / 1000:5.1f}s"
                  f"  {result['iterations']} iter  {result['tool_calls']} tools"
                  f"  {' '.join(result['tools'][:4])}"
                  f"  {' '.join(flags)}")
        print()

    print(f"{'shape':<17} {'n':>3} {'p50':>8} {'p95':>8} {'max':>8} {'ttfb p50':>9} "
          f"{'iter':>5} {'tools':>6} {'trunc':>6}")
    print("-" * 78)
    for shape in args.shapes:
        good = [r for r in rows if r.get("shape") == shape and r.get("client_ms")]
        if not good:
            print(f"{shape:<17} {'0':>3}   (no successful runs)")
            continue
        ms = [r["client_ms"] for r in good]
        print(f"{shape:<17} {len(good):>3} "
              f"{percentile(ms, 0.5) / 1000:7.1f}s {percentile(ms, 0.95) / 1000:7.1f}s "
              f"{max(ms) / 1000:7.1f}s "
              f"{percentile([r['ttfb_ms'] for r in good], 0.5) / 1000:8.1f}s "
              f"{statistics.mean(r['iterations'] or 0 for r in good):5.1f} "
              f"{statistics.mean(r['tool_calls'] or 0 for r in good):6.1f} "
              f"{sum(1 for r in good if r['truncated']):6}")
    print("\nWall clock above is client-side. For the authoritative figures including cost,")
    print("query ai_question_log joined to ai_request_log — see docs, and filter on")
    print(f"created_at >= '{run_start}'.")

    if args.out:
        args.out.write_text(json.dumps({"run_start": run_start, "deal_id": deal_id,
                                        "rows": rows}, indent=2))
        print(f"\nRaw rows: {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
